<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.6.9 on linux)" generated="20200514 11:04:26.338" rpa="false">
<suite id="s1" name="TC3" source="/home/andy/PycharmProjects/robot_example_2/test-cases/TC3/TC3.robot">
<test id="s1-t1" name="TC3">
<kw name="Create HTTP Context">
<arguments>
<arg>sut3:8083</arg>
</arguments>
<msg timestamp="20200514 11:04:26.360" level="FAIL">No keyword with name 'Create HTTP Context' found.</msg>
<status status="FAIL" starttime="20200514 11:04:26.360" endtime="20200514 11:04:26.360"></status>
</kw>
<doc>Returns after 10 seconds of heavy load to simulate a SUT</doc>
<status status="FAIL" starttime="20200514 11:04:26.358" endtime="20200514 11:04:26.360" critical="yes">No keyword with name 'Create HTTP Context' found.</status>
</test>
<status status="FAIL" starttime="20200514 11:04:26.339" endtime="20200514 11:04:26.360"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TC3">TC3</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200514 11:04:26.358" level="ERROR">Error in file '/home/andy/PycharmProjects/robot_example_2/test-cases/TC3/TC3.robot': Importing test library 'HttpLibrary.HTTP' failed: SyntaxError: invalid syntax (__init__.py, line 16)
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/andy/.local/bin
  /usr/lib/python36.zip
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /home/andy/.local/lib/python3.6/site-packages
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
